config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'lists#index'
  resources :lists, except: :delete do
    resources :bookmarks, only: [:create, :new]
  end
  resources :bookmarks, only: :delete
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :list, uniqueness: { scope: :movie, message: "can only have movie listed once" }
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_one_attached :photo
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, :overview, presence: true, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: :destroy
  before_action :set_list, only: [:new, :create]

  def new
    @bookmark = Bookmark.new
  end
  def create
    @bookmark = Bookmark.new(bookmark_params)
    # raise
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end
  def destroy
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end


  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def set_list
    @list = List.find(params[:list_id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end
  def new
    @list = List.new
  end
  def show
    @list = List.find(params[:id])
  end
  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to @list, notice: 'List created successfully.'
    else
      render :new
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<div class="container py-5">
  <div class="bg-white rounded p-3 shadow">
    <h3>Add a movie to your <%= @list.name %> list</h3>
    <%= simple_form_for [@list, @bookmark] do |f| %>
      <%= f.input :comment, placeholder: 'Enter a comment about the movie' %>
      <%= f.association :movie, prompt: 'Select a movie', input_html: { class: 'select2' } %>
      <%= f.submit class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://i.redd.it/vr49fjmt00m51.jpg);">
  <div class="container">
    <h1>Movie Lists</h1>
    <!-- <a class="btn btn-flat" href="#">Apply now</a> -->
    <p><%= link_to "New List", new_list_path, class:"btn btn-outline-primary my-3" %></p>
  </div>
</div>

<!-- <h1>Lists</h1> -->



<% @lists.each do |list| %>
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://st4.depositphotos.com/1517439/41744/v/600/depositphotos_417449668-stock-video-old-movie-countdown-animation-black.jpg)">
    <p><%= link_to list.name, list %></p>
  </div>
<% end %>

app/views/lists/new.html.erb
<h1>Create a List</h1>

<div class="form">
  <%= simple_form_for @list do |f| %>
    <%= f.input :name %>
    <%= f.input :photo, as: :file %>
    <%= f.submit class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/lists/show.html.erb
<div class="banner" id="second" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1619473667776-48cd8e52d380?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=900&ixid=MnwxfDB8MXxyYW5kb218fHx8fHx8fHwxNjIxMDA0ODI5&ixlib=rb-1.2.1&q=80&utm_campaign=api-credit&utm_medium=referral&utm_source=unsplash_source&w=1600);">
  <div class="container">
    <h1><%= @list.name %></h1>
    <%= link_to 'Add Movie', new_list_bookmark_path(@list), class: 'btn btn-outline-primary' %>
    <%= link_to 'Home', lists_path, class: 'btn btn-outline-primary' %>
  </div>
</div>


<div class="container">
  <% @list.movies.each do |movie| %>
    <div class="card">
      <!-- <img src="movie.poster_url" alt=""> -->
      <p>Title: <%= movie.title %></p>
      <small>Overview: <%= movie.overview %></small>
      <small>Rating: <%= movie.rating %></small>
    </div>
  <% end %>
</div>